{
 "title": "InterSystems IRIS for Health",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Job",
    "label": "Job",
    "query": {
     "query": "label_values(iris_cpu_usage, job)"
    }
   },
   {
    "name": "Instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=~\"$Job\",__name__=\"iris_cpu_usage\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DB size - iris-training",
   "type": "piechart",
   "gridPos": { "h": 23, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iris_db_size_mb{job=\"iris-training\", id!~\"ENSLIB|HSSYS|HSLIB|IRISSYS\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "DB size - iris-prod-1",
   "type": "piechart",
   "gridPos": { "h": 23, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iris_db_size_mb{job=\"iris-prod-1\", id!~\"ENSLIB|HSSYS|HSLIB|IRISSYS|NEW_APP_DATA|NEW_APP_CODE\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "DB size - iris-prod-2",
   "type": "piechart",
   "gridPos": { "h": 23, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iris_db_size_mb{job=\"iris-prod-2\", id!~\"ENSLIB|HSSYS|HSLIB|IRISSYS\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Efficiency",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iris_cache_efficiency{job=~\"$Job\", instance=~\"$Instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 5, "y": 12 },
     "targets": [
      {
       "expr": "iris_cpu_usage{job=~\"$Job\", instance=~\"$Instance\"}",
       "legendFormat": "CPU Utilization"
      }
     ]
    },
    {
     "title": "Database Free Space",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iris_db_free_space{job=~\"$Job\", instance=~\"$Instance\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Glorefs",
     "type": "timeseries",
     "description": "## Glorefs\n\nGlobal References per second is the number of times a data element was accessed whether that was from disk or from database cache. \n\nThis is a good indication of \"activity\"--high numbers mean high activity. \n\nAnother way of looking at GloRefs is as an indicator of database transaction rate.\n\n## Look for\n\n__No Hard limits__\n  \nLook for unusual deviations from baselines. \n\nLower than normal may indicate struggling with a resource - CPU, IO, or block contention, network\n\nCorrelate with disk IO\n\nHigh global references at the same time as a low database cache hit ratio (Cache Efficiency)  during peak hours will increase the physical read rate for database references.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "iris_glo_ref_per_sec{job=~\"$Job\", instance=~\"$Instance\"}",
       "legendFormat": "Glorefs"
      },
      {
       "expr": "iris_glo_ref_rem_per_sec{job=~\"$Job\", instance=~\"$Instance\"}",
       "legendFormat": "Remote Glorefs"
      }
     ]
    },
    {
     "title": "Database Reads",
     "type": "stat",
     "description": "## Physical Reads\n\nThe number of database blocks (8K and other sizes [if any]) read from disk per second. \n\nThis is the Disk I/O read activity--notice that on active systems there is always non-zero read data.\n",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iris_phys_reads_per_sec{job=~\"$Job\", instance=~\"$Instance\"}",
       "legendFormat": "Database Reads"
      }
     ]
    },
    {
     "title": "Global Updates",
     "type": "timeseries",
     "description": "## Global updates \n\nLocal SET and KILL",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "iris_glo_update_per_sec{job=~\"$Job\", instance=~\"$Instance\"}",
       "legendFormat": "Global Updates"
      }
     ]
    },
    {
     "title": "IRIS Database Latency",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iris_db_latency{id=\"IRISSYS\", job=~\"$Job\", instance=~\"$Instance\"}",
       "legendFormat": "Database Latency"
      }
     ]
    },
    {
     "title": "IRIS Disk Percent",
     "type": "bargauge",
     "description": "This shows disk percentage full for the disk that IRIS is installed on \n\n**Note:** GB remaining is much more important!",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iris_disk_percent_full{id=\"IRISSYS\", job=~\"$Job\", instance=~\"$Instance\"}",
       "legendFormat": "IRIS Disk Percent"
      }
     ]
    },
    {
     "title": "IRIS Disk Remaining",
     "type": "stat",
     "description": "MB remaining is much more important than %!",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iris_directory_space{id=\"IRISSYS\", job=~\"$Job\", instance=~\"$Instance\"}",
       "legendFormat": "IRIS Space Remaining"
      }
     ]
    },
    {
     "title": "System Alerts",
     "type": "stat",
     "description": "The number of alerts posted to the messages log since system startup.",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iris_system_alerts{job=~\"$Job\", instance=~\"$Instance\"}"
      }
     ]
    },
    {
     "title": "WIJ Free",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iris_jrn_free_space{id=\"WIJ\", job=~\"$Job\", instance=~\"$Instance\"}"
      }
     ]
    },
    {
     "title": "Pri Jnl Free",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iris_jrn_free_space{id=\"primary\", job=~\"$Job\", instance=~\"$Instance\"}"
      }
     ]
    },
    {
     "title": "Total Pri Jnl Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iris_jrn_size{id=\"primary\", job=~\"$Job\", instance=~\"$Instance\"}"
      }
     ]
    }
   ]
  }
 ]
}