services:
  iris-training:
    build: 
      args:
        IMAGE: ${IMAGE_IRIS_DEV_PREVIEW}
      context: iris-training
    image: iris-training  
    restart: always
    hostname: iris-training
    container_name: iris-training
    environment:
      - TZ=$TZ
      - ISC_DATA_DIRECTORY=/databases
      - ISC_CPF_MERGE_FILE=/merge.cpf
    ports: 
      - 11972:1972
      - 10000:52773
    volumes:
      - ./iris-training:/irisdev/app
      - ./jdbc:/jdbc
      - databases_training:/databases
      - journal_training:/journal
      - journal2_training:/journal2
      - WIJ_training:/WIJ
      - ./merge.cpf:/merge.cpf
    healthcheck:
      test: ["CMD", "iris", "session", "iris", "-U", "%SYS", "##class(%Api.Atelier).GetServer()"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s

  iris-prod-1:
    build: 
      args:
        IMAGE: ${IMAGE_IRIS_PROD_PREVIEW}
      context: iris-prod
    image: iris-prod-1
    restart: always
    init: true
    container_name: iris-prod-1
    hostname: iris-prod-1
    volumes:
    - ./iris-prod:/irisdev/app
    - ./jdbc:/jdbc
    - databases_prod_1:/databases
    - journal_prod_1:/journal
    - journal2_prod_1:/journal2
    - WIJ_prod_1:/WIJ
    - ./merge.cpf:/merge.cpf
    - type: bind
      source: ./iris-prod
      target: /iris-prod-1
    - type: bind
      source: ./webgateway/cert
      target: /opt/cert
    - type: bind
      source: ./mirror/mirror-certs
      target: /mirror-certs
    environment:
      - TZ=$TZ
      - ISC_DATA_DIRECTORY=/databases
      - ISC_CPF_MERGE_FILE=/merge.cpf
    ports:
      - 10001:1972
    command: --key /iris-prod-1/key/iris.key -a /iris-prod-1/configure.sh
    healthcheck:
      test: ["CMD", "iris", "session", "iris", "-U", "%SYS", "##class(%Api.Atelier).GetServer()"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
  
  iris-prod-2:
    build: 
      args:
        IMAGE: ${IMAGE_IRIS_PROD_PREVIEW}
      context: iris-prod
    image: iris-prod-2
    restart: always
    init: true
    container_name: iris-prod-2
    hostname: iris-prod-2
    volumes:
    - ./iris-prod:/irisdev/app
    - ./jdbc:/jdbc
    - databases_prod_2:/databases
    - journal_prod_2:/journal
    - journal2_prod_2:/journal2
    - WIJ_prod_2:/WIJ
    - ./merge.cpf:/merge.cpf
    - type: bind
      source: ./iris-prod
      target: /iris-prod-2
    - type: bind
      source: ./webgateway/cert
      target: /opt/cert
    - type: bind
      source: ./mirror/mirror-certs
      target: /mirror-certs
    environment:
      - TZ=$TZ
      - ISC_DATA_DIRECTORY=/databases
      - ISC_CPF_MERGE_FILE=/merge.cpf
    ports:
      - 10002:1972
    command: --key /iris-prod-2/key/iris.key -a /iris-prod-2/configure.sh
    healthcheck:
      test: ["CMD", "iris", "session", "iris", "-U", "%SYS", "##class(%Api.Atelier).GetServer()"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
      
  webgateway:
    image: ${WEBGATEWAY}
    init: true
    hostname: ${WEBGATEWAY_NAME}
    container_name: ${WEBGATEWAY_NAME}
    ports:
    - ${WEBGATEWAY_PORT_HTTP}:80
    - ${WEBGATEWAY_PORT_HTTPS}:443
    environment:
    - ISC_CSP_CONF_FILE=/webgateway/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway/CSP.ini
    volumes:
    - type: bind
      source: ./webgateway
      target: /webgateway
    - type: bind
      source: ./webgateway/cert
      target: /opt/cert
  arbiter:
    image: ${ARBITER}
    container_name: ${ARBITER_NAME}
    hostname: ${ARBITER_NAME}
    environment:
      - TZ=$TZ
    healthcheck:
      test: ["CMD", "pgrep", "-f", "ISCAgentUser"]
      interval: 30s
      timeout: 10s
      retries: 5
    # command: ["-p 2188"]

  notebook:
    image: notebook
    container_name: notebook
    build: 
      context: notebook
    ports:
      - "8889:8888"
    volumes:
      - ./notebook/Notebooks:/Notebooks
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --notebook-dir=/Notebooks"

  postgres:
    container_name: training-postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgreSQL:/docker-entrypoint-initdb.d/
      - databases_postgreSQL:/var/lib/postgresql/data
    ports:
      - 52004:5432
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 30s
        timeout: 30s
        retries: 3

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitor/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitor/prometheus/isc_alert_rules.yml:/etc/prometheus/isc_alert_rules.yml
      - prometheus:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=ADMIN
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://host.docker.internal:13100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    # volumes:
    #   - ./loki/local-config.yaml:/etc/loki/local-config.yaml
    #   - ./volumes/loki:/loki

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./data/IRIS/mgr:/var/log
    command: -config.file=/etc/promtail/config.yml

  fhir_validator_app:
    build:
      context: fhir-validator-app
    depends_on:
      - fhir_validator_service
    container_name: fhir_validator_app
    environment:
      EXTERNAL_VALIDATOR_URL: http://localhost:4567
      VALIDATOR_BASE_PATH: /validator
    ports:
      - "1234:80"
    command: 
  fhir_validator_service:
    image: infernocommunity/fhir-validator-service:latest
    container_name: fhir_validator_service
    volumes:
      - ./igs:/home/igs/package
    ports:
      - "4567:4567"

volumes:
  prometheus:
  grafana:
  databases_postgreSQL:
  databases_training:
    external: true
    name: ${VOLUME_NAME}databases_training
  journal_training:
    external: true
    name: ${VOLUME_NAME}journal_training
  journal2_training:
    external: true
    name: ${VOLUME_NAME}journal2_training
  WIJ_training:
    external: true
    name: ${VOLUME_NAME}WIJ_training  
  databases_prod_1:   
    external: true
    name: ${VOLUME_NAME}databases_prod_1  
  journal_prod_1:
    external: true
    name: ${VOLUME_NAME}journal_prod_1
  journal2_prod_1:
    external: true
    name: ${VOLUME_NAME}journal2_prod_1
  WIJ_prod_1:
    external: true
    name: ${VOLUME_NAME}WIJ_prod_1
  databases_prod_2:
    external: true
    name: ${VOLUME_NAME}databases_prod_2
  journal_prod_2:
    external: true
    name: ${VOLUME_NAME}journal_prod_2
  journal2_prod_2:
    external: true
    name: ${VOLUME_NAME}journal2_prod_2   
  WIJ_prod_2:
    external: true
    name: ${VOLUME_NAME}WIJ_prod_2
  
